name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.txt -t src/build/lambda_packages

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Copy shared Terraform files
        run: |
          cp ./terraform/shared/datastore.tf ./terraform/prod/
          cp ./terraform/shared/lambda_packaging.tf ./terraform/prod/

      - name: Terraform Init
        working-directory: ./terraform/prod 
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform/prod
        run: terraform apply -auto-approve
